title: Amundsen by Lyft
description: Open source data discovery and metadata engine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.amundsen.io/" # the base hostname & protocol for your site, e.g. http://example.com

#Links within the site
documentation: "https://lyft.github.io/amundsen/"
getstarted: "https://lyft.github.io/amundsen/"
youtube: "https://www.youtube.com/playlist?list=PL0UJdxehTNlKnGU_h7k2fzJyvAiufeh1U"
github: "https://github.com/lyft/amundsen"
community: "https://join.slack.com/t/amundsenworkspace/shared_invite/enQtNTk2ODQ1NDU1NDI0LTc3MzQyZmM0ZGFjNzg5MzY1MzJlZTg4YjQ4YTU0ZmMxYWU2MmVlMzhhY2MzMTc1MDg0MzRjNTA4MzRkMGE0Nzk"
medium: "https://github.com/lyft/amundsen#blog-posts-and-interviews"

destination: dist

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
