title: Amundsen, the leading open source data catalog
description: Open source data discovery and metadata engine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.amundsen.io" # the base hostname & protocol for your site, e.g. http://example.com

#Links within the site
documentation: "https://www.amundsen.io/amundsen/"
getstarted: "https://www.amundsen.io/amundsen/"
youtube: "https://www.youtube.com/playlist?list=PL0UJdxehTNlKnGU_h7k2fzJyvAiufeh1U"
github: "https://github.com/amundsen-io/amundsen"
community: "https://join.slack.com/t/amundsenworkspace/shared_invite/zt-s8f3srsx-_0b6_WA5~eYGrv_g63L2ng"
medium: "https://github.com/amundsen-io/amundsen#blog-posts-and-interviews"

destination: docs

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
